apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: tailscale-operator-vault-auth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  vaultConnectionRef: vault-secrets-operator-system/default

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: kubernetes-tailscale-operator
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
