deployment:
  replicas: 2

providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
    allowCrossNamespace: false

gatewayClass:
  enabled: true

gateway:
  enabled: true

rbac:
  enabled: false

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP

    expose:
      default: true
      tailnet: true

  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP

    expose:
      default: true
      tailnet: true

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.io/loadBalancerIPs: 192.168.8.240
  spec:
    externalTrafficPolicy: Cluster

  additionalServices:
    tailnet:
      annotations:
        tailscale.com/proxy-group: traefik-ingress
        tailscale.com/hostname: traefik-tailnet

      spec:
        type: LoadBalancer
        loadBalancerClass: tailscale

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: false
