deployment:
  replicas: 2

providers:
  kubernetesGateway:
    enabled: true
    statusAddress:
      hostname: "traefik-tailnet.tailfb03f6.ts.net"
      service:
        enabled: false

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
    allowCrossNamespace: false

gatewayClass:
  enabled: true

gateway:
  enabled: true

rbac:
  enabled: false

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    expose:
      default: true
      tailnet: true

  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
    expose:
      default: true
      tailnet: true

service:
  enabled: true
  annotations: {}
  spec:
    type: ClusterIP

  additionalServices:
    tailnet:
      annotations:
        tailscale.com/proxy-group: traefik-ingress
        tailscale.com/hostname: traefik-tailnet
      spec:
        type: LoadBalancer
        loadBalancerClass: tailscale

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: false
