stages:
  - build # CI Tooling & Docker images
  - plan # Infrastructure Dry-Runs
  - apply # Infrastructure Provisioning
  - bootstrap # Configuration Management (Ansible/K3s)

variables:
  TF_ROOT: "terraform/environments/cloud/aws/foundation-prod"
  TF_IN_AUTOMATION: "true"
  VAULT_ADDR: "https://debian.tailfb03f6.ts.net:8200"
  ANSIBLE_CONFIG: "${CI_PROJECT_DIR}/ansible/ansible.cfg"
  ANSIBLE_ROLES_PATH: "${CI_PROJECT_DIR}/ansible/roles"

include:
  - local: '.gitlab/ci/templates/aws-setup-and-auth.yml'
  - local: '.gitlab/ci/docker/build-runner.yml'
  - local: '.gitlab/ci/terraform/aws-foundation.yml'
  - local: '.gitlab/ci/ansible/bootstrap-workers.yml'
