apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-networking
rules:

  # Core Resources for Endpoints, Discovery, and TLS management
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - endpoints
      - namespaces
      - nodes
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Discovery Engine Endpoint Tracking
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Standard Legacy K8s Ingress Elements
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Traefik Custom Resource Definitions (CRDs)
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Kubernetes Gateway API (All resources + Status adjustments)
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - referencegrants
      - grpcroutes
      - tlsroutes
      - tcproutes
      - udproutes
      - backendtlspolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - grpcroutes/status
      - tlsroutes/status
      - tcproutes/status
      - udproutes/status
      - backendtlspolicies/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-networking-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-networking
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: networking
