apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../apps/base/argocd-ui
  - namespace.yaml
  - cert-manager/local-selfsigned-issuer.yaml
  - cert-manager/manual-local-cert.yaml
  - vault-secrets-operator
  - monitoring-stack
  - coredns
  - networking/vault-external.yaml
  - networking/external-docker-bridge.yaml
  - networking/traefik-gateway-rbac.yaml
  - networking/gateway-class.yaml
  - networking/local-cluster-gateway.yaml
  - networking/routes-docker.yaml
  - networking/routes-production.yaml
  - networking/routes-dev.yaml
  - networking/routes-monitoring.yaml
  - networking/routes-argocd.yaml
  - networking/authentik-dev-middleware.yaml
