apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: gitops-system-vault-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  vaultConnectionRef: vault-secrets-operator-system/default

  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: kubernetes-gitops-system
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
