apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-homelab-private-repo-vault
  namespace: argocd
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/gitops-system/argocd-repository
  vaultAuthRef: gitops-system-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: github-homelab-private-repo
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      excludeRaw: true
