apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  #volumeName: minio-dev-local-pv
  resources:
    requests:
      storage: 5Gi
