apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: central-postgres-ha
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17-standard-trixie

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  storage:
    size: 15Gi
    storageClass: local-path

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      cnpg-ha: "true"
    tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"

  bootstrap:
    recovery:
      database: wallabag
      owner: wallabag_user
      secret:
        name: cnpg-wallabag-credentials-vault
      source: central-postgres-ha-backup

  externalClusters:
    - name: central-postgres-ha-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-postgres-backups
          serverName: production

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-postgres-backups
        serverName: production
