apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
  - ../../../base/minio
  - ../../../base/redis
  - central-postgres-ha.yaml
  - barman-objectstore.yaml
  - scheduled-backup-ha.yaml
  - oci-postgres-dr-mirror-cronjob.yaml
  - minio-bucket-job.yaml

patches:
  - path: ./patches/minio/minio-vault-secret.yaml
