apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: central-postgres-ha-nightly-backup
spec:
  schedule: "0 0 20 * * *"
  immediate: true
  backupOwnerReference: cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: central-postgres-ha
