apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rustfs
  labels:
    apps.home.lab/managed-by: gitops
    apps.home.lab/storage-tier: object-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataEngine: "v1"
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: ext4
  dataLocality: best-effort
  replicaAutoBalance: least-effort
