apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  template:
    spec:
      containers:
        - name: wallabag
          env:
            - name: SYMFONY__ENV__DATABASE_HOST
              value: central-postgres-ha-rw.prod-database.svc.cluster.local

            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://wallabag.home"

            - name: SYMFONY__ENV__REDIS_HOST
              value: redis.prod-cache.svc.cluster.local
