apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  template:
    spec:
      containers:
        - name: wallabag
          env:
            - name: SYMFONY__ENV__DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: wallabag-credentials-vault
                  key: DATABASE_USER

            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-credentials-vault
                  key: DATABASE_PASSWORD
