azure_agents:
  hosts:
    cloud-node-03:
    cloud-node-04:


all:
  children:
    k3s_control_plane:
      hosts:
        k8s-master:
          ansible_host: 172.16.0.12
    k3s_workers:
      hosts:
        k8s-worker1:
          ansible_host: 172.16.0.13
        k8s-worker2:
          ansible_host: 172.16.0.14
      # all:
      #   children:
      #     k3s_control_plane:
      #       hosts:
      #         cloud-node-01:
      #         cloud-node-02:
      #     k3s_workers:
      #       hosts:
      #         cloud-node-03:
      #         cloud-node-04:
      #         aws-node-01:   # Future expansions!
