apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/minio
  - ../../../base/redis
  - minio-bucket-job.yaml
  - central-postgres-dev.yaml
  - barman-objectstore.yaml
  - oci-postgres-dr-mirror-cronjob.yaml
  - health-database-dev.yaml
  - n8n-database-dev.yaml
  - authentik-database-dev.yaml
  - docmost-database-dev.yaml
  - scheduled-backup-dev.yaml

patches:
  - path: patches/minio/minio-dev-patch.yaml
  - path: patches/minio/minio-pvc-patch.yaml
  - path: patches/redis/redis-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - worker-1
