apiVersion: v1
kind: Namespace
metadata:
  name: prod-database
  labels:
    apps.home.lab/managed-by: argocd
    apps.home.lab/environment: production
    apps.home.lab/workload: database
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: prod-cache
#   labels:
#     apps.home.lab/managed-by: argocd
#     apps.home.lab/environment: production
#     apps.home.lab/workload: cache
#     pod-security.kubernetes.io/enforce: restricted
#     pod-security.kubernetes.io/audit: restricted
#     pod-security.kubernetes.io/warn: restricted
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: prod-pgadmin
#   labels:
#     apps.home.lab/managed-by: argocd
#     apps.home.lab/environment: production
#     apps.home.lab/workload: pgadmin
#     pod-security.kubernetes.io/enforce: restricted
#     pod-security.kubernetes.io/audit: restricted
#     pod-security.kubernetes.io/warn: restricted
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: prod-wallabag
#   labels:
#     apps.home.lab/managed-by: argocd
#     apps.home.lab/environment: production
#     apps.home.lab/workload: wallabag
#     pod-security.kubernetes.io/enforce: restricted
#     pod-security.kubernetes.io/audit: restricted
#     pod-security.kubernetes.io/warn: restricted
