apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oci-postgres-dr-credentials-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

spec:
  type: kv-v2
  mount: kv
  path: kubernetes/production/oci-postgres-dr-credentials
  vaultAuthRef: prod-database-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: oci-postgres-dr-credentials-vault
    labels:
      cnpg.io/reload: "true"

    transformation:
      excludeRaw: true
      templates:
        ACCESS_KEY_ID:
          text: '{{ get .Secrets "ACCESS_KEY_ID" }}'
        SECRET_ACCESS_KEY:
          text: '{{ get .Secrets "SECRET_ACCESS_KEY" }}'
        AWS_REGION:
          text: '{{ get .Secrets "AWS_REGION" }}'
        BUCKET:
          text: '{{ get .Secrets "BUCKET" }}'
        S3_ENDPOINT:
          text: '{{ get .Secrets "S3_ENDPOINT" }}'
