apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-pgadmin-admin-credentials-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/production/pgadmin-admin-role

  vaultAuthRef: prod-database-vault-auth

  refreshAfter: 1m
  hmacSecretData: true

  destination:
    create: true
    overwrite: true
    name: cnpg-pgadmin-admin-credentials-vault
    type: kubernetes.io/basic-auth

    labels:
      cnpg.io/reload: "true"

    transformation:
      excludeRaw: true
      templates:
        username:
          text: '{{ get .Secrets "username" }}'
        password:
          text: '{{ get .Secrets "password" }}'
