# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: local-root-ca
#   namespace: networking
# spec:
#   isCA: true

#   secretName: local-root-ca

#   commonName: "GitOps Local Root CA"

#   duration: 87600h

#   renewal:
#     policy: Disabled

#   privateKey:
#     algorithm: ECDSA
#     size: 384
#     rotationPolicy: Never

#   usages:
#     - cert sign
#     - crl sign
#     - digital signature

#   issuerRef:
#     name: local-selfsigned-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io