apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pgadmin

  template:
    metadata:
      labels:
        app: pgadmin

    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.17
          ports:
            - name: http
              containerPort: 8080
