apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dockge-endpointslice.yaml
  - portainer-endpointslice.yaml
  - qbittorrent-endpointslice.yaml
  - jellyfin-endpointslice.yaml
  - seer-endpointslice.yaml
  - prowlarr-endpointslice.yaml
  - radarr-endpointslice.yaml
  - sonarr-endpointslice.yaml
  - lidarr-endpointslice.yaml
  - whispar-v2-endpointslice.yaml
  - whispar-v3-endpointslice.yaml
