apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dockge-endpointslice.yaml
  - portainer-endpointslice.yaml
  - qbittorrent-endpointslice.yaml
  - jellyfin-endpointslice.yaml
  - seerr-endpointslice.yaml
  - prowlarr-endpointslice.yaml
  - radarr-endpointslice.yaml
  - sonarr-endpointslice.yaml
  - lidarr-endpointslice.yaml
  - whisparr-v2-endpointslice.yaml
  - whisparr-v3-endpointslice.yaml
