apiVersion: v1
kind: EndpointSlice
metadata:
  name: qbittorrent-external
  namespace: networking
  labels:
    kubernetes.io/service-name: qbittorrent
    endpointslice.kubernetes.io/managed-by: homelab-gitops
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - "100.110.252.128"
    conditions:
      ready: true
