apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: radarr-external
  namespace: networking
  labels:
    kubernetes.io/service-name: radarr
    endpointslice.kubernetes.io/managed-by: homelab-gitops
addressType: IPv4
ports:
  - name: http
    port: 7878
    protocol: TCP
endpoints:
  - addresses:
      - "100.110.252.128"
    conditions:
      ready: true
