apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: sonarr-external
  namespace: networking
  labels:
    kubernetes.io/service-name: sonarr
    endpointslice.kubernetes.io/managed-by: homelab-gitops
addressType: IPv4
ports:
  - name: http
    port: 8989
    protocol: TCP
endpoints:
  - addresses:
      - "100.110.252.128"
    conditions:
      ready: true
