global:
  nodeSelector:
    node-restriction.kubernetes.io/persistent-storage: "true"

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

persistence:
  createStorageClass: false
  defaultClass: false

preUpgradeChecker:
  jobEnabled: false

longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

longhornGlobalManager:
  replicas: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 2

longhornUI:
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

defaultSettings:
  defaultDataPath: /home/longhorn
  createDefaultDiskLabeledNodes: true
  replicaSoftAntiAffinity: false
  replicaAutoBalance: least-effort
  allowVolumeCreationWithDegradedAvailability: false
  nodeDrainPolicy: block-if-contains-last-replica
  storageMinimalAvailablePercentage: 20
  storageReservedPercentageForDefaultDisk: 10
  concurrentReplicaRebuildPerNodeLimit: 2
  systemManagedComponentsNodeSelector: "node-restriction.kubernetes.io/persistent-storage=true"
  #taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
