apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pgadmin-vault-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  vaultConnectionRef: vault-secrets-operator-system/default
  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: kubernetes-prod-pgadmin
    serviceAccount: prod-pgadmin-vault
    audiences:
      - vault
    tokenExpirationSeconds: 600
