apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dockge-service.yaml
  - portainer-service.yaml
  - qbittorrent-service.yaml
  - jellyfin-service.yaml
  - seerr-service.yaml
  - prowlarr-service.yaml
  - radarr-service.yaml
  - sonarr-service.yaml
  - lidarr-service.yaml
  - whisparr-v2-service.yaml
  - whisparr-v3-service.yaml
