apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-database

resources:
  - vault-static-secret-rustfs-secondary.yaml
  - rustfs-secondary-objectstore.yaml
  - oci-to-rustfs-cronjob.yaml
