apiVersion: v1
kind: Namespace
metadata:
  name: object-storage
  labels:
    apps.home.lab/managed-by: argocd
    apps.home.lab/component: object-storage
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
