apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-storage-compute
  namespace: object-storage
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 10Gi
    pods: "10"
    persistentvolumeclaims: "6"
    requests.storage: 100Gi
